services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: newpassword123
      MYSQL_DATABASE: Blanche
      MYSQL_USER: user
      MYSQL_PASSWORD: infolog_321
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
